### PR TITLE
fix build on gcc 4.8

### PR DESCRIPTION
**Pull request by notaz**
some versions of gcc want to inline DitherBitmap(), and this leads to trouble:
Sources/Engine/Graphics/Graphics.cpp:1167: Error: symbol `rowLoopE' is already defined
Sources/Engine/Graphics/Graphics.cpp:1170: Error: symbol`pixLoopEL' is already defined
...

### CODE REVIEW

**Comment by icculus** [comment]
The actual fix here is to use relative asm labels (0: instead of rowLoopE:, etc), but this is good enough for now.
